import { StyleSheet } from 'react-native'

export const createListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5deb3',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#add8e6',
  },
  header: {
    backgroundColor: '#add8e6',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
  },
  title: {
    fontSize: 24,
    fontWeight: '900',
    color: '#323232',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    lineHeight: 22,
    fontWeight: '600',
  },
  form: {
    padding: 20,
    flex: 1,
  },
  inputGroup: {
    marginBottom: 24,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#323232',
    marginBottom: 8,
  },
  requiredLabel: {
    fontSize: 16,
    fontWeight: '900',
    color: '#323232',
    marginBottom: 8,
  },
  helperText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
    lineHeight: 20,
    fontWeight: '600',
  },
  textInput: {
    backgroundColor: '#f5deb3',
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    borderRadius: 5,
    padding: 12,
    fontSize: 16,
    color: '#323232',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  textInputFocused: {
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    elevation: 0,
    transform: [{ translateX: 3 }, { translateY: 3 }],
  },
  textArea: {
    height: 80,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  charCount: {
    fontSize: 12,
    color: '#666',
    textAlign: 'right',
    marginTop: 4,
    fontWeight: '600',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryButton: {
    backgroundColor: '#f5deb3',
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    borderRadius: 5,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  categoryButtonSelected: {
    backgroundColor: '#add8e6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    elevation: 0,
    transform: [{ translateX: 3 }, { translateY: 3 }],
  },
  categoryButtonText: {
    fontSize: 14,
    color: '#323232',
    fontWeight: '600',
  },
  categoryButtonTextSelected: {
    color: '#323232',
    fontWeight: '900',
  },
  buttonContainer: {
    padding: 20,
    backgroundColor: '#add8e6',
    borderTopWidth: 3,
    borderTopColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
  },
  createButton: {
    backgroundColor: '#f5deb3',
    borderRadius: 5,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  createButtonDisabled: {
    backgroundColor: '#ccc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    elevation: 0,
  },
  createButtonText: {
    color: '#323232',
    fontSize: 16,
    fontWeight: '900',
  },
  createButtonTextDisabled: {
    color: '#666',
  },
}) 