import { StyleSheet } from 'react-native'

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5deb3', // beige background like the form
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#add8e6', // lightblue like the form
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
  },
  title: {
    fontSize: 24,
    fontWeight: '900',
    color: '#323232',
  },
  createButton: {
    backgroundColor: '#f5deb3',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    position: 'relative',
    overflow: 'visible',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  createButtonText: {
    color: '#323232',
    fontWeight: '600',
    fontSize: 14,
  },
  // Leaf animation styles
  leaf1: {
    position: 'absolute',
    top: -38,
    right: 5,
  },
  leaf2: {
    position: 'absolute',
    top: -27,
    left: -1,
  },
  leaf3: {
    position: 'absolute',
    bottom: -29,
    right: 5,
  },
  // Search section styles
  searchSection: {
    padding: 20,
    backgroundColor: '#add8e6',
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderWidth: 2,
    borderColor: '#000',
    borderRadius: 5,
    backgroundColor: '#f5deb3',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  searchIcon: {
    fontSize: 20,
    color: '#323232',
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    padding: 8,
    fontSize: 15,
    fontWeight: '600',
    color: '#323232',
  },
  clearButton: {
    padding: 8,
  },
  clearButtonText: {
    fontSize: 16,
    color: '#323232',
    fontWeight: '600',
  },
  searchResults: {
    fontSize: 12,
    color: '#323232',
    marginTop: 8,
    fontWeight: '600',
  },
  // List container styles with blue background
  listContainer: {
    padding: 16,
    backgroundColor: '#add8e6', // Blue background behind the lists
    flex: 1,
  },
  emptyContainer: {
    flex: 1,
    backgroundColor: '#add8e6', // Blue background for empty state too
  },
  // List card styles with enhanced 3D shadow
  card: {
    backgroundColor: '#f5deb3',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    padding: 16,
    marginBottom: 16,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  listName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#323232',
    flex: 1,
    marginRight: 8,
  },
  category: {
    fontSize: 12,
    fontWeight: '600',
    color: '#323232',
    backgroundColor: '#add8e6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    textTransform: 'capitalize',
  },
  categoryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  deleteButton: {
    padding: 4,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#000',
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  deleteButtonText: {
    fontSize: 12,
    color: '#000',
    fontWeight: '900',
  },
  cardContent: {
    gap: 8,
  },
  description: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    fontWeight: '600',
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  itemCount: {
    fontSize: 14,
    fontWeight: '900',
    color: '#323232',
  },
  creator: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
  },
  ownerContainer: {
    alignItems: 'center',
    marginTop: 8,
  },
  // Empty state styles with enhanced 3D shadow
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#323232',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    fontWeight: '600',
  },
  emptyButton: {
    backgroundColor: '#f5deb3',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
  },
  emptyButtonText: {
    color: '#323232',
    fontWeight: '600',
    fontSize: 16,
  },
  // Error state styles with enhanced 3D shadow
  errorState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#e74c3c',
    marginBottom: 12,
    textAlign: 'center',
  },
  errorSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    fontWeight: '600',
  },
  retryButton: {
    backgroundColor: '#f5deb3',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#e74c3c',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#e74c3c',
    borderBottomColor: '#e74c3c',
  },
  retryButtonText: {
    color: '#e74c3c',
    fontWeight: '600',
    fontSize: 16,
  },
  // Loading state styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5deb3',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#666',
    fontWeight: '600',
  },
}) 