import { StyleSheet } from 'react-native'

export const listDetailsStyles = StyleSheet.create({
  // Root container
  root: {
    flex: 1,
    backgroundColor: '#f5deb3',
  },
  
  // Header styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#add8e6',
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  headerInfo: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  listName: {
    fontSize: 20,
    fontWeight: '900',
    color: '#323232',
    textAlign: 'center',
  },
  listCategory: {
    fontSize: 14,
    color: '#666',
    textTransform: 'capitalize',
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: '#f5deb3',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: '#323232',
    fontWeight: '900',
  },
  inviteButton: {
    backgroundColor: '#add8e6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    marginRight: 4,
  },
  inviteButtonText: {
    fontSize: 16,
    color: '#323232',
    fontWeight: '900',
  },
  deleteListButton: {
    backgroundColor: '#f85565',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    marginRight: 4,
  },
  deleteListButtonText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  leaveButton: {
    backgroundColor: '#f85565',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    marginRight: 4,
  },
  leaveButtonText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  addButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 14,
    textTransform: 'uppercase',
  },
  
  // Shopping mode section
  shoppingModeSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#f5deb3',
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  shoppingModeInfo: {
    flex: 1,
  },
  shoppingModeLabel: {
    fontSize: 16,
    fontWeight: '900',
    color: '#323232',
  },
  shoppingModeSubtext: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
    fontWeight: '600',
  },
  
  // Empty state styles
  emptyStateCard: {
    backgroundColor: '#f5deb3',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    padding: 32,
    alignItems: 'center',
    margin: 32,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#323232',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    fontWeight: '600',
  },
  emptyButton: {
    backgroundColor: '#f5deb3',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  emptyButtonText: {
    color: '#323232',
    fontWeight: '900',
    fontSize: 16,
    textTransform: 'uppercase',
  },
  
  // Loading styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5deb3',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#666',
    fontWeight: '600',
  },
  
  // List container styles
  emptyContainer: {
    flex: 1,
    backgroundColor: '#add8e6',
  },
  listContainer: {
    padding: 16,
    backgroundColor: '#add8e6',
    flex: 1,
  },
  
  // Menu button styles
  menuButton: {
    backgroundColor: '#f5deb3',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    marginLeft: 8,
  },
  menuButtonText: {
    fontSize: 18,
    color: '#323232',
    fontWeight: '900',
  },
  
  // Menu modal styles
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 120,
    paddingRight: 20,
  },
  menuContainer: {
    backgroundColor: '#f5deb3',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    minWidth: 180,
  },
  menuItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
  },
  menuItemDestructive: {
    borderBottomWidth: 0,
  },
  menuItemText: {
    fontSize: 16,
    color: '#323232',
    fontWeight: '600',
  },
  menuItemTextDestructive: {
    color: '#f85565',
    fontWeight: '900',
  },
}) 