import { StyleSheet } from 'react-native'

export const listStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#add8e6', // Blue background like My Lists
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#add8e6',
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
  },
  backButton: {
    paddingVertical: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: '#323232',
    fontWeight: '900',
  },
  headerInfo: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  listName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#323232',
    textAlign: 'center',
  },
  listCategory: {
    fontSize: 14,
    color: '#666',
    textTransform: 'capitalize',
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inviteButton: {
    backgroundColor: '#34C759',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  inviteButtonText: {
    fontSize: 16,
  },
  deleteListButton: {
    backgroundColor: '#FF3B30',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  deleteListButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
  },
  leaveButton: {
    backgroundColor: '#FF3B30',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  leaveButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
  },
  addButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  shoppingModeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#f5deb3', // Beige background
    borderBottomWidth: 3,
    borderBottomColor: '#000',
    borderRightWidth: 3,
    borderRightColor: '#000',
  },
  shoppingModeInfo: {
    flex: 1,
  },
  shoppingModeLabel: {
    fontSize: 16,
    fontWeight: '900',
    color: '#323232',
  },
  shoppingModeSubtext: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
    fontWeight: '600',
  },
  listContainer: {
    padding: 16,
    backgroundColor: '#add8e6', // Blue background like My Lists
  },
  emptyContainer: {
    flex: 1,
    backgroundColor: '#add8e6', // Blue background for empty state
  },
  itemCard: {
    backgroundColor: '#f5deb3', // Beige background like My Lists cards
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    padding: 16,
    marginBottom: 16,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    borderLeftWidth: 4, // Keep color coding
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  statusIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 2,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  statusIconText: {
    fontSize: 16,
    fontWeight: '900',
  },
  itemContent: {
    flex: 1,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  itemInfo: {
    flex: 1,
    marginRight: 12,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#323232',
    marginBottom: 4,
  },
  itemNameCompleted: {
    textDecorationLine: 'line-through',
    color: '#666',
  },
  quantity: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#000',
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  statusBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  itemDetails: {
    marginBottom: 12,
  },
  itemDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    marginBottom: 4,
    fontWeight: '600',
  },
  storeNote: {
    fontSize: 12,
    color: '#007AFF',
    fontStyle: 'italic',
    fontWeight: '600',
  },
  itemActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusButtons: {
    flexDirection: 'row',
    gap: 8,
    flex: 1,
  },
  statusButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 5,
    flex: 1,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  statusButtonText: {
    fontSize: 12,
    fontWeight: '900',
  },
  deleteButton: {
    padding: 8,
    marginLeft: 8,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#000',
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  deleteButtonText: {
    fontSize: 16,
    color: '#000',
    fontWeight: '900',
  },
  addedBy: {
    fontSize: 11,
    color: '#666',
    textAlign: 'right',
    fontWeight: '600',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#323232',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    fontWeight: '600',
  },
  emptyButton: {
    backgroundColor: '#f5deb3',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  emptyButtonText: {
    color: '#323232',
    fontWeight: '900',
    fontSize: 16,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5deb3',
  },
  loadingText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  regularModeInfo: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    backgroundColor: '#f5deb3',
    borderRadius: 5,
    marginRight: 8,
    borderWidth: 2,
    borderColor: '#000',
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderRightColor: '#000',
    borderBottomColor: '#000',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  regularModeText: {
    fontSize: 14,
    fontWeight: '900',
    // Color will be set dynamically based on status
  },
}) 